package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.83

import (
	"context"
	"main/custom_middleware"
	"main/graph/graphql_model"
	"main/service"
)

// AddUserAccountByGoogleAuth is the resolver for the addUserAccountByGoogleAuth field.
func (r *mutationResolver) AddUserAccountByGoogleAuth(ctx context.Context, registerToken string, userSettingID string, name string) (*graphql_model.UserAccountResponse, error) {
	return service.AddUserAccountByGoogleAuth(registerToken, userSettingID, name)
}

// LoginByGoogleAuth is the resolver for the loginByGoogleAuth field.
func (r *mutationResolver) LoginByGoogleAuth(ctx context.Context, authCode string) (*graphql_model.UserAccountResponse, error) {
	return service.GetUserAccountByGoogleAuthCode(authCode)
}

// EditUserAccount is the resolver for the editUserAccount field.
func (r *mutationResolver) EditUserAccount(ctx context.Context, userSettingID string, name string) (*graphql_model.UserAccountResponse, error) {
	userAccountID := custom_middleware.GeUserAccountIDFromContext(ctx)
	return service.EditUserAccountByGoogleAuth(*userAccountID, userSettingID, name)
}

// AddNovel is the resolver for the addNovel field.
func (r *mutationResolver) AddNovel(ctx context.Context, title string, description *string) (*bool, error) {
	userAccountID := custom_middleware.GeUserAccountIDFromContext(ctx)
	return service.AddNovel(*userAccountID, title, description)
}

// EditNovel is the resolver for the editNovel field.
func (r *mutationResolver) EditNovel(ctx context.Context, id string, title string, description *string) (*bool, error) {
	userAccountID := custom_middleware.GeUserAccountIDFromContext(ctx)
	return service.EditNovel(*userAccountID, id, title, description)
}

// DeleteNovel is the resolver for the deleteNovel field.
func (r *mutationResolver) DeleteNovel(ctx context.Context, id string) (*bool, error) {
	userAccountID := custom_middleware.GeUserAccountIDFromContext(ctx)
	return service.DeleteNovel(*userAccountID, id)
}

// RegisterNovelSettings is the resolver for the registerNovelSettings field.
func (r *mutationResolver) RegisterNovelSettings(ctx context.Context, inputs []graphql_model.NovelSettingRegisterInput) (*bool, error) {
	userAccountID := custom_middleware.GeUserAccountIDFromContext(ctx)
	return service.RegisterNovelSettings(*userAccountID, inputs)
}

// DeleteNovelSettingByID is the resolver for the deleteNovelSettingById field.
func (r *mutationResolver) DeleteNovelSettingByID(ctx context.Context, id string) (*bool, error) {
	userAccountID := custom_middleware.GeUserAccountIDFromContext(ctx)
	return service.DeleteNovelSettingByID(*userAccountID, id)
}

// DeleteNovelSettingByIds is the resolver for the deleteNovelSettingByIds field.
func (r *mutationResolver) DeleteNovelSettingByIds(ctx context.Context, ids []string) (*bool, error) {
	userAccountID := custom_middleware.GeUserAccountIDFromContext(ctx)
	return service.DeleteNovelSettingByIDs(*userAccountID, ids)
}

// GetUserAccountRegisterTokenFromGoogleAuthCode is the resolver for the getUserAccountRegisterTokenFromGoogleAuthCode field.
func (r *queryResolver) GetUserAccountRegisterTokenFromGoogleAuthCode(ctx context.Context, authCode string) (*string, error) {
	return service.GetUserAccountRegisterTokenByGoogleAuthCode(authCode)
}

// GetUserAccountFromAuthHeader is the resolver for the getUserAccountFromAuthHeader field.
func (r *queryResolver) GetUserAccountFromAuthHeader(ctx context.Context) (*graphql_model.UserAccountResponse, error) {
	userAccountID := custom_middleware.GeUserAccountIDFromContext(ctx)
	return service.GetUserAccountByUserAccountID(*userAccountID)
}

// GetMyNovels is the resolver for the getMyNovels field.
func (r *queryResolver) GetMyNovels(ctx context.Context) ([]graphql_model.NovelResponse, error) {
	userAccountID := custom_middleware.GeUserAccountIDFromContext(ctx)
	return service.GetMyNovels(*userAccountID)
}

// GetMyNovelByID is the resolver for the getMyNovelById field.
func (r *queryResolver) GetMyNovelByID(ctx context.Context, novelID string) (*graphql_model.NovelResponse, error) {
	userAccountID := custom_middleware.GeUserAccountIDFromContext(ctx)
	return service.GetMyNovelByID(*userAccountID, novelID)
}

// GetNovelSettingsByNovelID is the resolver for the getNovelSettingsByNovelId field.
func (r *queryResolver) GetNovelSettingsByNovelID(ctx context.Context, novelID string) ([]graphql_model.NovelSettingResponse, error) {
	userAccountID := custom_middleware.GeUserAccountIDFromContext(ctx)
	return service.GetNovelSettingsByNovelID(*userAccountID, novelID)
}

// GetNovelSettingsByParentSettingID is the resolver for the getNovelSettingsByParentSettingId field.
func (r *queryResolver) GetNovelSettingsByParentSettingID(ctx context.Context, parentID string) ([]graphql_model.NovelSettingResponse, error) {
	userAccountID := custom_middleware.GeUserAccountIDFromContext(ctx)
	return service.GetNovelSettingsByParentID(*userAccountID, parentID)
}

// Mutation returns MutationResolver implementation.
func (r *Resolver) Mutation() MutationResolver { return &mutationResolver{r} }

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

type mutationResolver struct{ *Resolver }
type queryResolver struct{ *Resolver }

// !!! WARNING !!!
// The code below was going to be deleted when updating resolvers. It has been copied here so you have
// one last chance to move it out of harms way if you want. There are two reasons this happens:
//  - When renaming or deleting a resolver the old code will be put in here. You can safely delete
//    it when you're done.
//  - You have helper methods in this file. Move them out to keep these resolver files clean.
/*
	func (r *queryResolver) GetMyNovelSettings(ctx context.Context, novelID string) ([]graphql_model.NovelSettingResponse, error) {
	userAccountID := custom_middleware.GeUserAccountIDFromContext(ctx)
	return service.GetMyNovelSettings(*userAccountID, novelID)
}
*/
