package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.81

import (
	"context"
	"fmt"
	"main/custom_middleware"
	"main/graph/graphql_model"
	"main/service"
)

// AddUserAccountByGoogleAuth is the resolver for the addUserAccountByGoogleAuth field.
func (r *mutationResolver) AddUserAccountByGoogleAuth(ctx context.Context, registerToken string, userSettingID string, name string) (*graphql_model.UserAccountResponse, error) {
	return service.AddUserAccountByGoogleAuth(registerToken, userSettingID, name)
}

// LoginByGoogleAuth is the resolver for the loginByGoogleAuth field.
func (r *mutationResolver) LoginByGoogleAuth(ctx context.Context, authCode string) (*graphql_model.UserAccountResponse, error) {
	return service.GetUserAccountByGoogleAuthCode(authCode)
}

// Todos is the resolver for the todos field.
func (r *queryResolver) Todos(ctx context.Context) ([]*graphql_model.Todo, error) {
	panic(fmt.Errorf("not implemented: Todos - todos"))
}

// GetUserAccountRegisterTokenFromGoogleAuthCode is the resolver for the getUserAccountRegisterTokenFromGoogleAuthCode field.
func (r *queryResolver) GetUserAccountRegisterTokenFromGoogleAuthCode(ctx context.Context, authCode string) (*string, error) {
	return service.GetUserAccountRegisterTokenByGoogleAuthCode(authCode)
}

// GetUserAccountFromAuthHeader is the resolver for the getUserAccountFromAuthHeader field.
func (r *queryResolver) GetUserAccountFromAuthHeader(ctx context.Context) (*graphql_model.UserAccountResponse, error) {
	userAccountID := custom_middleware.GeUserAccountIDFromContext(ctx)
	return service.GetUserAccountByUserAccountID(*userAccountID)
}

// Mutation returns MutationResolver implementation.
func (r *Resolver) Mutation() MutationResolver { return &mutationResolver{r} }

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

type mutationResolver struct{ *Resolver }
type queryResolver struct{ *Resolver }
