// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package graphql_model

type Mutation struct {
}

type NovelContentsRegisterInput struct {
	ID               *string `json:"id,omitempty"`
	ChapterName      string  `json:"chapterName"`
	NovelID          string  `json:"novelId"`
	ParentContentsID *string `json:"parentContentsId,omitempty"`
	DisplayOrder     *int32  `json:"displayOrder,omitempty"`
	Contents         *string `json:"contents,omitempty"`
	Description      *string `json:"description,omitempty"`
}

type NovelContentsResponse struct {
	ID               string  `json:"id"`
	ChapterName      string  `json:"chapterName"`
	NovelID          string  `json:"novelId"`
	ParentContentsID *string `json:"parentContentsId,omitempty"`
	DisplayOrder     *int32  `json:"displayOrder,omitempty"`
	Contents         *string `json:"contents,omitempty"`
	Description      *string `json:"description,omitempty"`
}

type NovelResponse struct {
	ID          string  `json:"id"`
	Title       string  `json:"title"`
	Description *string `json:"description,omitempty"`
}

type NovelSettingRegisterInput struct {
	ID              *string  `json:"id,omitempty"`
	Name            string   `json:"name"`
	NovelID         string   `json:"novelId"`
	ParentSettingID *string  `json:"parentSettingId,omitempty"`
	DisplayOrder    *int32   `json:"displayOrder,omitempty"`
	Attributes      []string `json:"attributes"`
	Description     *string  `json:"description,omitempty"`
}

type NovelSettingResponse struct {
	ID              string   `json:"id"`
	Name            string   `json:"name"`
	NovelID         string   `json:"novelId"`
	ParentSettingID *string  `json:"parentSettingId,omitempty"`
	DisplayOrder    *int32   `json:"displayOrder,omitempty"`
	Attributes      []string `json:"attributes"`
	Description     *string  `json:"description,omitempty"`
}

type Query struct {
}

type UserAccountResponse struct {
	Token         string `json:"token"`
	UserSettingID string `json:"userSettingId"`
	Name          string `json:"name"`
	ImageURL      string `json:"imageUrl"`
}
