// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package db_model

const TableNameNovelContent = "novel_contents"

// NovelContent mapped from table <novel_contents>
type NovelContent struct {
	ID                 string  `gorm:"column:id;primaryKey" json:"id"`
	ChapterName        string  `gorm:"column:chapter_name;not null" json:"chapter_name"`
	NovelID            string  `gorm:"column:novel_id;not null" json:"novel_id"`
	OwnerUserAccountID string  `gorm:"column:owner_user_account_id;not null" json:"owner_user_account_id"`
	ParentContentsID   *string `gorm:"column:parent_contents_id" json:"parent_contents_id"`
	DisplayOrder       *int32  `gorm:"column:display_order" json:"display_order"`
	Contents           *string `gorm:"column:contents" json:"contents"`
	Description        *string `gorm:"column:description" json:"description"`
}

// TableName NovelContent's table name
func (*NovelContent) TableName() string {
	return TableNameNovelContent
}
