// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package db_model

import (
	"time"
)

const TableNameNovel = "novels"

// Novel mapped from table <novels>
type Novel struct {
	ID                 string    `gorm:"column:id;primaryKey" json:"id"`
	Title              string    `gorm:"column:title;not null" json:"title"`
	Description        *string   `gorm:"column:description" json:"description"`
	OwnerUserAccountID string    `gorm:"column:owner_user_account_id;not null" json:"owner_user_account_id"`
	CreatedAt          time.Time `gorm:"column:created_at;not null" json:"created_at"`
}

// TableName Novel's table name
func (*Novel) TableName() string {
	return TableNameNovel
}
