// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package db_model

import (
	"time"
)

const TableNameUserAccount = "user_accounts"

// UserAccount mapped from table <user_accounts>
type UserAccount struct {
	ID            string    `gorm:"column:id;primaryKey" json:"id"`
	UserSettingID string    `gorm:"column:user_setting_id;not null" json:"user_setting_id"`
	Name          string    `gorm:"column:name;not null" json:"name"`
	Gmail         string    `gorm:"column:gmail;not null" json:"gmail"`
	ImageURL      *string   `gorm:"column:image_url" json:"image_url"`
	CreatedAt     time.Time `gorm:"column:created_at;not null" json:"created_at"`
}

// TableName UserAccount's table name
func (*UserAccount) TableName() string {
	return TableNameUserAccount
}
