// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.0
// 	protoc        v3.19.4
// source: src/proto/authenticationUser.proto

package pb

import (
	context "context"
	_ "github.com/envoyproxy/protoc-gen-validate/validate"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type VerifyGoogleAuthCodeRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	GoogleAuthCode string `protobuf:"bytes,1,opt,name=googleAuthCode,proto3" json:"googleAuthCode,omitempty"`
}

func (x *VerifyGoogleAuthCodeRequest) Reset() {
	*x = VerifyGoogleAuthCodeRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_src_proto_authenticationUser_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *VerifyGoogleAuthCodeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VerifyGoogleAuthCodeRequest) ProtoMessage() {}

func (x *VerifyGoogleAuthCodeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_src_proto_authenticationUser_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VerifyGoogleAuthCodeRequest.ProtoReflect.Descriptor instead.
func (*VerifyGoogleAuthCodeRequest) Descriptor() ([]byte, []int) {
	return file_src_proto_authenticationUser_proto_rawDescGZIP(), []int{0}
}

func (x *VerifyGoogleAuthCodeRequest) GetGoogleAuthCode() string {
	if x != nil {
		return x.GoogleAuthCode
	}
	return ""
}

type UserResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id        string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name      string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	AuthToken string `protobuf:"bytes,3,opt,name=authToken,proto3" json:"authToken,omitempty"`
}

func (x *UserResponse) Reset() {
	*x = UserResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_src_proto_authenticationUser_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UserResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserResponse) ProtoMessage() {}

func (x *UserResponse) ProtoReflect() protoreflect.Message {
	mi := &file_src_proto_authenticationUser_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserResponse.ProtoReflect.Descriptor instead.
func (*UserResponse) Descriptor() ([]byte, []int) {
	return file_src_proto_authenticationUser_proto_rawDescGZIP(), []int{1}
}

func (x *UserResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UserResponse) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *UserResponse) GetAuthToken() string {
	if x != nil {
		return x.AuthToken
	}
	return ""
}

type VerifyAuthTokenRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *VerifyAuthTokenRequest) Reset() {
	*x = VerifyAuthTokenRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_src_proto_authenticationUser_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *VerifyAuthTokenRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VerifyAuthTokenRequest) ProtoMessage() {}

func (x *VerifyAuthTokenRequest) ProtoReflect() protoreflect.Message {
	mi := &file_src_proto_authenticationUser_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VerifyAuthTokenRequest.ProtoReflect.Descriptor instead.
func (*VerifyAuthTokenRequest) Descriptor() ([]byte, []int) {
	return file_src_proto_authenticationUser_proto_rawDescGZIP(), []int{2}
}

type AuthTokenResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id   string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
}

func (x *AuthTokenResponse) Reset() {
	*x = AuthTokenResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_src_proto_authenticationUser_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AuthTokenResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthTokenResponse) ProtoMessage() {}

func (x *AuthTokenResponse) ProtoReflect() protoreflect.Message {
	mi := &file_src_proto_authenticationUser_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuthTokenResponse.ProtoReflect.Descriptor instead.
func (*AuthTokenResponse) Descriptor() ([]byte, []int) {
	return file_src_proto_authenticationUser_proto_rawDescGZIP(), []int{3}
}

func (x *AuthTokenResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *AuthTokenResponse) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

var File_src_proto_authenticationUser_proto protoreflect.FileDescriptor

var file_src_proto_authenticationUser_proto_rawDesc = []byte{
	0x0a, 0x22, 0x73, 0x72, 0x63, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x61, 0x75, 0x74, 0x68,
	0x65, 0x6e, 0x74, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x55, 0x73, 0x65, 0x72, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x12, 0x02, 0x70, 0x62, 0x1a, 0x17, 0x76, 0x61, 0x6c, 0x69, 0x64, 0x61,
	0x74, 0x65, 0x2f, 0x76, 0x61, 0x6c, 0x69, 0x64, 0x61, 0x74, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x22, 0x4e, 0x0a, 0x1b, 0x56, 0x65, 0x72, 0x69, 0x66, 0x79, 0x47, 0x6f, 0x6f, 0x67, 0x6c,
	0x65, 0x41, 0x75, 0x74, 0x68, 0x43, 0x6f, 0x64, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x12, 0x2f, 0x0a, 0x0e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x41, 0x75, 0x74, 0x68, 0x43, 0x6f,
	0x64, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x42, 0x07, 0xfa, 0x42, 0x04, 0x72, 0x02, 0x10,
	0x01, 0x52, 0x0e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x41, 0x75, 0x74, 0x68, 0x43, 0x6f, 0x64,
	0x65, 0x22, 0x50, 0x0a, 0x0c, 0x55, 0x73, 0x65, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69,
	0x64, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x1c, 0x0a, 0x09, 0x61, 0x75, 0x74, 0x68, 0x54, 0x6f, 0x6b,
	0x65, 0x6e, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x61, 0x75, 0x74, 0x68, 0x54, 0x6f,
	0x6b, 0x65, 0x6e, 0x22, 0x18, 0x0a, 0x16, 0x56, 0x65, 0x72, 0x69, 0x66, 0x79, 0x41, 0x75, 0x74,
	0x68, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x37, 0x0a,
	0x11, 0x41, 0x75, 0x74, 0x68, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02,
	0x69, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x32, 0xb0, 0x01, 0x0a, 0x19, 0x41, 0x75, 0x74, 0x68, 0x65,
	0x6e, 0x74, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x55, 0x73, 0x65, 0x72, 0x53, 0x65, 0x72,
	0x76, 0x69, 0x63, 0x65, 0x12, 0x4b, 0x0a, 0x14, 0x56, 0x65, 0x72, 0x69, 0x66, 0x79, 0x47, 0x6f,
	0x6f, 0x67, 0x6c, 0x65, 0x41, 0x75, 0x74, 0x68, 0x43, 0x6f, 0x64, 0x65, 0x12, 0x1f, 0x2e, 0x70,
	0x62, 0x2e, 0x56, 0x65, 0x72, 0x69, 0x66, 0x79, 0x47, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x41, 0x75,
	0x74, 0x68, 0x43, 0x6f, 0x64, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x10, 0x2e,
	0x70, 0x62, 0x2e, 0x55, 0x73, 0x65, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22,
	0x00, 0x12, 0x46, 0x0a, 0x0f, 0x56, 0x65, 0x72, 0x69, 0x66, 0x79, 0x41, 0x75, 0x74, 0x68, 0x54,
	0x6f, 0x6b, 0x65, 0x6e, 0x12, 0x1a, 0x2e, 0x70, 0x62, 0x2e, 0x56, 0x65, 0x72, 0x69, 0x66, 0x79,
	0x41, 0x75, 0x74, 0x68, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x1a, 0x15, 0x2e, 0x70, 0x62, 0x2e, 0x41, 0x75, 0x74, 0x68, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x42, 0x08, 0x5a, 0x06, 0x70, 0x62, 0x2f,
	0x3b, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_src_proto_authenticationUser_proto_rawDescOnce sync.Once
	file_src_proto_authenticationUser_proto_rawDescData = file_src_proto_authenticationUser_proto_rawDesc
)

func file_src_proto_authenticationUser_proto_rawDescGZIP() []byte {
	file_src_proto_authenticationUser_proto_rawDescOnce.Do(func() {
		file_src_proto_authenticationUser_proto_rawDescData = protoimpl.X.CompressGZIP(file_src_proto_authenticationUser_proto_rawDescData)
	})
	return file_src_proto_authenticationUser_proto_rawDescData
}

var file_src_proto_authenticationUser_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_src_proto_authenticationUser_proto_goTypes = []interface{}{
	(*VerifyGoogleAuthCodeRequest)(nil), // 0: pb.VerifyGoogleAuthCodeRequest
	(*UserResponse)(nil),                // 1: pb.UserResponse
	(*VerifyAuthTokenRequest)(nil),      // 2: pb.VerifyAuthTokenRequest
	(*AuthTokenResponse)(nil),           // 3: pb.AuthTokenResponse
}
var file_src_proto_authenticationUser_proto_depIdxs = []int32{
	0, // 0: pb.AuthenticationUserService.VerifyGoogleAuthCode:input_type -> pb.VerifyGoogleAuthCodeRequest
	2, // 1: pb.AuthenticationUserService.VerifyAuthToken:input_type -> pb.VerifyAuthTokenRequest
	1, // 2: pb.AuthenticationUserService.VerifyGoogleAuthCode:output_type -> pb.UserResponse
	3, // 3: pb.AuthenticationUserService.VerifyAuthToken:output_type -> pb.AuthTokenResponse
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_src_proto_authenticationUser_proto_init() }
func file_src_proto_authenticationUser_proto_init() {
	if File_src_proto_authenticationUser_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_src_proto_authenticationUser_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*VerifyGoogleAuthCodeRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_src_proto_authenticationUser_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UserResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_src_proto_authenticationUser_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*VerifyAuthTokenRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_src_proto_authenticationUser_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AuthTokenResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_src_proto_authenticationUser_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_src_proto_authenticationUser_proto_goTypes,
		DependencyIndexes: file_src_proto_authenticationUser_proto_depIdxs,
		MessageInfos:      file_src_proto_authenticationUser_proto_msgTypes,
	}.Build()
	File_src_proto_authenticationUser_proto = out.File
	file_src_proto_authenticationUser_proto_rawDesc = nil
	file_src_proto_authenticationUser_proto_goTypes = nil
	file_src_proto_authenticationUser_proto_depIdxs = nil
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// AuthenticationUserServiceClient is the client API for AuthenticationUserService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type AuthenticationUserServiceClient interface {
	// Google認証コードの検証
	VerifyGoogleAuthCode(ctx context.Context, in *VerifyGoogleAuthCodeRequest, opts ...grpc.CallOption) (*UserResponse, error)
	// 認証トークンの検証
	VerifyAuthToken(ctx context.Context, in *VerifyAuthTokenRequest, opts ...grpc.CallOption) (*AuthTokenResponse, error)
}

type authenticationUserServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewAuthenticationUserServiceClient(cc grpc.ClientConnInterface) AuthenticationUserServiceClient {
	return &authenticationUserServiceClient{cc}
}

func (c *authenticationUserServiceClient) VerifyGoogleAuthCode(ctx context.Context, in *VerifyGoogleAuthCodeRequest, opts ...grpc.CallOption) (*UserResponse, error) {
	out := new(UserResponse)
	err := c.cc.Invoke(ctx, "/pb.AuthenticationUserService/VerifyGoogleAuthCode", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *authenticationUserServiceClient) VerifyAuthToken(ctx context.Context, in *VerifyAuthTokenRequest, opts ...grpc.CallOption) (*AuthTokenResponse, error) {
	out := new(AuthTokenResponse)
	err := c.cc.Invoke(ctx, "/pb.AuthenticationUserService/VerifyAuthToken", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AuthenticationUserServiceServer is the server API for AuthenticationUserService service.
type AuthenticationUserServiceServer interface {
	// Google認証コードの検証
	VerifyGoogleAuthCode(context.Context, *VerifyGoogleAuthCodeRequest) (*UserResponse, error)
	// 認証トークンの検証
	VerifyAuthToken(context.Context, *VerifyAuthTokenRequest) (*AuthTokenResponse, error)
}

// UnimplementedAuthenticationUserServiceServer can be embedded to have forward compatible implementations.
type UnimplementedAuthenticationUserServiceServer struct {
}

func (*UnimplementedAuthenticationUserServiceServer) VerifyGoogleAuthCode(context.Context, *VerifyGoogleAuthCodeRequest) (*UserResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method VerifyGoogleAuthCode not implemented")
}
func (*UnimplementedAuthenticationUserServiceServer) VerifyAuthToken(context.Context, *VerifyAuthTokenRequest) (*AuthTokenResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method VerifyAuthToken not implemented")
}

func RegisterAuthenticationUserServiceServer(s *grpc.Server, srv AuthenticationUserServiceServer) {
	s.RegisterService(&_AuthenticationUserService_serviceDesc, srv)
}

func _AuthenticationUserService_VerifyGoogleAuthCode_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(VerifyGoogleAuthCodeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthenticationUserServiceServer).VerifyGoogleAuthCode(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.AuthenticationUserService/VerifyGoogleAuthCode",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthenticationUserServiceServer).VerifyGoogleAuthCode(ctx, req.(*VerifyGoogleAuthCodeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AuthenticationUserService_VerifyAuthToken_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(VerifyAuthTokenRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthenticationUserServiceServer).VerifyAuthToken(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.AuthenticationUserService/VerifyAuthToken",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthenticationUserServiceServer).VerifyAuthToken(ctx, req.(*VerifyAuthTokenRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _AuthenticationUserService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "pb.AuthenticationUserService",
	HandlerType: (*AuthenticationUserServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "VerifyGoogleAuthCode",
			Handler:    _AuthenticationUserService_VerifyGoogleAuthCode_Handler,
		},
		{
			MethodName: "VerifyAuthToken",
			Handler:    _AuthenticationUserService_VerifyAuthToken_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "src/proto/authenticationUser.proto",
}
