// Code generated by protoc-gen-validate. DO NOT EDIT.
// source: src/proto/geographicPoint.proto

package pb

import (
	"bytes"
	"errors"
	"fmt"
	"net"
	"net/mail"
	"net/url"
	"regexp"
	"sort"
	"strings"
	"time"
	"unicode/utf8"

	"google.golang.org/protobuf/types/known/anypb"
)

// ensure the imports are used
var (
	_ = bytes.MinRead
	_ = errors.New("")
	_ = fmt.Print
	_ = utf8.UTFMax
	_ = (*regexp.Regexp)(nil)
	_ = (*strings.Reader)(nil)
	_ = net.IPv4len
	_ = time.Duration(0)
	_ = (*url.URL)(nil)
	_ = (*mail.Address)(nil)
	_ = anypb.Any{}
	_ = sort.Sort
)

// Validate checks the field values on AddGeographicPointRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *AddGeographicPointRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on AddGeographicPointRequest with the
// rules defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// AddGeographicPointRequestMultiError, or nil if none found.
func (m *AddGeographicPointRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *AddGeographicPointRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if utf8.RuneCountInString(m.GetName()) < 1 {
		err := AddGeographicPointRequestValidationError{
			field:  "Name",
			reason: "value length must be at least 1 runes",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if m.GetLat() < 0 {
		err := AddGeographicPointRequestValidationError{
			field:  "Lat",
			reason: "value must be greater than or equal to 0",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if m.GetLon() < 0 {
		err := AddGeographicPointRequestValidationError{
			field:  "Lon",
			reason: "value must be greater than or equal to 0",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if len(errors) > 0 {
		return AddGeographicPointRequestMultiError(errors)
	}

	return nil
}

// AddGeographicPointRequestMultiError is an error wrapping multiple validation
// errors returned by AddGeographicPointRequest.ValidateAll() if the
// designated constraints aren't met.
type AddGeographicPointRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m AddGeographicPointRequestMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m AddGeographicPointRequestMultiError) AllErrors() []error { return m }

// AddGeographicPointRequestValidationError is the validation error returned by
// AddGeographicPointRequest.Validate if the designated constraints aren't met.
type AddGeographicPointRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e AddGeographicPointRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e AddGeographicPointRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e AddGeographicPointRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e AddGeographicPointRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e AddGeographicPointRequestValidationError) ErrorName() string {
	return "AddGeographicPointRequestValidationError"
}

// Error satisfies the builtin error interface
func (e AddGeographicPointRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sAddGeographicPointRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = AddGeographicPointRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = AddGeographicPointRequestValidationError{}

// Validate checks the field values on RegsiterGeographicPointResponse with the
// rules defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *RegsiterGeographicPointResponse) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on RegsiterGeographicPointResponse with
// the rules defined in the proto definition for this message. If any rules
// are violated, the result is a list of violation errors wrapped in
// RegsiterGeographicPointResponseMultiError, or nil if none found.
func (m *RegsiterGeographicPointResponse) ValidateAll() error {
	return m.validate(true)
}

func (m *RegsiterGeographicPointResponse) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if len(errors) > 0 {
		return RegsiterGeographicPointResponseMultiError(errors)
	}

	return nil
}

// RegsiterGeographicPointResponseMultiError is an error wrapping multiple
// validation errors returned by RegsiterGeographicPointResponse.ValidateAll()
// if the designated constraints aren't met.
type RegsiterGeographicPointResponseMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m RegsiterGeographicPointResponseMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m RegsiterGeographicPointResponseMultiError) AllErrors() []error { return m }

// RegsiterGeographicPointResponseValidationError is the validation error
// returned by RegsiterGeographicPointResponse.Validate if the designated
// constraints aren't met.
type RegsiterGeographicPointResponseValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e RegsiterGeographicPointResponseValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e RegsiterGeographicPointResponseValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e RegsiterGeographicPointResponseValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e RegsiterGeographicPointResponseValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e RegsiterGeographicPointResponseValidationError) ErrorName() string {
	return "RegsiterGeographicPointResponseValidationError"
}

// Error satisfies the builtin error interface
func (e RegsiterGeographicPointResponseValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sRegsiterGeographicPointResponse.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = RegsiterGeographicPointResponseValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = RegsiterGeographicPointResponseValidationError{}
