// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package db

type TaskDefinition struct {
	ID               string
	Title            string
	OwnerUserID      string
	DisplayFlag      bool
	NotificationFlag bool
	CategoryID       *string
	Detail           *string
}
