// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: query.sql

package db

import (
	"context"
)

const createTaskDefinition = `-- name: CreateTaskDefinition :one
insert
	into
	task_definition (
    id,
	title,
	owner_user_id,
	display_flag,
	notification_flag,
	category_id,
	detail
)
values (
    $1, 
    $2, 
    $3, 
    $4,
    $5,
    $6,
    $7
) returning id, title, owner_user_id, display_flag, notification_flag, category_id, detail
`

type CreateTaskDefinitionParams struct {
	ID               string
	Title            string
	OwnerUserID      string
	DisplayFlag      bool
	NotificationFlag bool
	CategoryID       *string
	Detail           *string
}

func (q *Queries) CreateTaskDefinition(ctx context.Context, arg CreateTaskDefinitionParams) (TaskDefinition, error) {
	row := q.db.QueryRow(ctx, createTaskDefinition,
		arg.ID,
		arg.Title,
		arg.OwnerUserID,
		arg.DisplayFlag,
		arg.NotificationFlag,
		arg.CategoryID,
		arg.Detail,
	)
	var i TaskDefinition
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.OwnerUserID,
		&i.DisplayFlag,
		&i.NotificationFlag,
		&i.CategoryID,
		&i.Detail,
	)
	return i, err
}
