// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

import (
	"wasurena-task-api/db"
)

type CreateUserRegisterTokenResponse struct {
	Token    string `json:"token"`
	LineName string `json:"lineName"`
}

type Mutation struct {
}

type NewCategory struct {
	Name         string `json:"name"`
	DisplayOrder *int32 `json:"displayOrder,omitempty"`
}

type NewTask struct {
	Title                   string                `json:"title"`
	DisplayFlag             bool                  `json:"displayFlag"`
	NotificationFlag        bool                  `json:"notificationFlag"`
	CategoryID              *string               `json:"categoryId,omitempty"`
	DeadLineCheck           *db.DeadLineCheckEnum `json:"deadLineCheck,omitempty"`
	DeadLineCheckSubSetting map[string]any        `json:"deadLineCheckSubSetting,omitempty"`
	Detail                  *string               `json:"detail,omitempty"`
}

type NewTaskExecute struct {
	TaskDefinitionID string  `json:"taskDefinitionId"`
	Memo             *string `json:"memo,omitempty"`
}

type NewUserAccount struct {
	AuthToken     string `json:"authToken"`
	UserSettingID string `json:"userSettingId"`
	UserName      string `json:"userName"`
}

type Query struct {
}

type TaskCategoryResponse struct {
	ID           string `json:"id"`
	Name         string `json:"name"`
	DisplayOrder *int32 `json:"displayOrder,omitempty"`
}

type UserAccountResponse struct {
	Token           string  `json:"token"`
	UserSettingID   string  `json:"userSettingId"`
	UserName        string  `json:"userName"`
	ImageURL        *string `json:"imageUrl,omitempty"`
	IsLineBotFollow bool    `json:"isLineBotFollow"`
}
