
-- +migrate Up
CREATE TABLE LOGIN_USER (
  id VARCHAR2(100) PRIMARY KEY,
  name VARCHAR2(100) NOT NULL,
  last_login_date_time NUMBER NOT NULL
);

CREATE TABLE GEOGRAPHIC_POINT (
  id VARCHAR2(100) PRIMARY KEY,
  name VARCHAR2(100) NOT NULL,
  user_id VARCHAR2(100) NOT NULL,
  lat FLOAT NOT NULL,
  lon FLOAT NOT NULL,
  display_order NUMBER NOT NULL,
  register_date_time NUMBER NOT NULL
);

CREATE INDEX GEOGRAPHIC_POINT_USER_ID_INDEX ON geographic_point(user_id);

-- +migrate Down
DROP TABLE LOGIN_USER;

DROP TABLE GEOGRAPHIC_POINT;
