// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"
	"database/sql"

	"gorm.io/gorm"

	"gorm.io/gen"

	"gorm.io/plugin/dbresolver"
)

var (
	Q            = new(Query)
	Novel        *novel
	NovelContent *novelContent
	NovelSetting *novelSetting
	UserAccount  *userAccount
)

func SetDefault(db *gorm.DB, opts ...gen.DOOption) {
	*Q = *Use(db, opts...)
	Novel = &Q.Novel
	NovelContent = &Q.NovelContent
	NovelSetting = &Q.NovelSetting
	UserAccount = &Q.UserAccount
}

func Use(db *gorm.DB, opts ...gen.DOOption) *Query {
	return &Query{
		db:           db,
		Novel:        newNovel(db, opts...),
		NovelContent: newNovelContent(db, opts...),
		NovelSetting: newNovelSetting(db, opts...),
		UserAccount:  newUserAccount(db, opts...),
	}
}

type Query struct {
	db *gorm.DB

	Novel        novel
	NovelContent novelContent
	NovelSetting novelSetting
	UserAccount  userAccount
}

func (q *Query) Available() bool { return q.db != nil }

func (q *Query) clone(db *gorm.DB) *Query {
	return &Query{
		db:           db,
		Novel:        q.Novel.clone(db),
		NovelContent: q.NovelContent.clone(db),
		NovelSetting: q.NovelSetting.clone(db),
		UserAccount:  q.UserAccount.clone(db),
	}
}

func (q *Query) ReadDB() *Query {
	return q.ReplaceDB(q.db.Clauses(dbresolver.Read))
}

func (q *Query) WriteDB() *Query {
	return q.ReplaceDB(q.db.Clauses(dbresolver.Write))
}

func (q *Query) ReplaceDB(db *gorm.DB) *Query {
	return &Query{
		db:           db,
		Novel:        q.Novel.replaceDB(db),
		NovelContent: q.NovelContent.replaceDB(db),
		NovelSetting: q.NovelSetting.replaceDB(db),
		UserAccount:  q.UserAccount.replaceDB(db),
	}
}

type queryCtx struct {
	Novel        INovelDo
	NovelContent INovelContentDo
	NovelSetting INovelSettingDo
	UserAccount  IUserAccountDo
}

func (q *Query) WithContext(ctx context.Context) *queryCtx {
	return &queryCtx{
		Novel:        q.Novel.WithContext(ctx),
		NovelContent: q.NovelContent.WithContext(ctx),
		NovelSetting: q.NovelSetting.WithContext(ctx),
		UserAccount:  q.UserAccount.WithContext(ctx),
	}
}

func (q *Query) Transaction(fc func(tx *Query) error, opts ...*sql.TxOptions) error {
	return q.db.Transaction(func(tx *gorm.DB) error { return fc(q.clone(tx)) }, opts...)
}

func (q *Query) Begin(opts ...*sql.TxOptions) *QueryTx {
	tx := q.db.Begin(opts...)
	return &QueryTx{Query: q.clone(tx), Error: tx.Error}
}

type QueryTx struct {
	*Query
	Error error
}

func (q *QueryTx) Commit() error {
	return q.db.Commit().Error
}

func (q *QueryTx) Rollback() error {
	return q.db.Rollback().Error
}

func (q *QueryTx) SavePoint(name string) error {
	return q.db.SavePoint(name).Error
}

func (q *QueryTx) RollbackTo(name string) error {
	return q.db.RollbackTo(name).Error
}
