// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"
	"database/sql"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"main/db/db_model"
)

func newNovel(db *gorm.DB, opts ...gen.DOOption) novel {
	_novel := novel{}

	_novel.novelDo.UseDB(db, opts...)
	_novel.novelDo.UseModel(&db_model.Novel{})

	tableName := _novel.novelDo.TableName()
	_novel.ALL = field.NewAsterisk(tableName)
	_novel.ID = field.NewString(tableName, "id")
	_novel.Title = field.NewString(tableName, "title")
	_novel.Description = field.NewString(tableName, "description")
	_novel.OwnerUserAccountID = field.NewString(tableName, "owner_user_account_id")
	_novel.CreatedAt = field.NewTime(tableName, "created_at")

	_novel.fillFieldMap()

	return _novel
}

type novel struct {
	novelDo novelDo

	ALL                field.Asterisk
	ID                 field.String
	Title              field.String
	Description        field.String
	OwnerUserAccountID field.String
	CreatedAt          field.Time

	fieldMap map[string]field.Expr
}

func (n novel) Table(newTableName string) *novel {
	n.novelDo.UseTable(newTableName)
	return n.updateTableName(newTableName)
}

func (n novel) As(alias string) *novel {
	n.novelDo.DO = *(n.novelDo.As(alias).(*gen.DO))
	return n.updateTableName(alias)
}

func (n *novel) updateTableName(table string) *novel {
	n.ALL = field.NewAsterisk(table)
	n.ID = field.NewString(table, "id")
	n.Title = field.NewString(table, "title")
	n.Description = field.NewString(table, "description")
	n.OwnerUserAccountID = field.NewString(table, "owner_user_account_id")
	n.CreatedAt = field.NewTime(table, "created_at")

	n.fillFieldMap()

	return n
}

func (n *novel) WithContext(ctx context.Context) INovelDo { return n.novelDo.WithContext(ctx) }

func (n novel) TableName() string { return n.novelDo.TableName() }

func (n novel) Alias() string { return n.novelDo.Alias() }

func (n novel) Columns(cols ...field.Expr) gen.Columns { return n.novelDo.Columns(cols...) }

func (n *novel) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := n.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (n *novel) fillFieldMap() {
	n.fieldMap = make(map[string]field.Expr, 5)
	n.fieldMap["id"] = n.ID
	n.fieldMap["title"] = n.Title
	n.fieldMap["description"] = n.Description
	n.fieldMap["owner_user_account_id"] = n.OwnerUserAccountID
	n.fieldMap["created_at"] = n.CreatedAt
}

func (n novel) clone(db *gorm.DB) novel {
	n.novelDo.ReplaceConnPool(db.Statement.ConnPool)
	return n
}

func (n novel) replaceDB(db *gorm.DB) novel {
	n.novelDo.ReplaceDB(db)
	return n
}

type novelDo struct{ gen.DO }

type INovelDo interface {
	gen.SubQuery
	Debug() INovelDo
	WithContext(ctx context.Context) INovelDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() INovelDo
	WriteDB() INovelDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) INovelDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) INovelDo
	Not(conds ...gen.Condition) INovelDo
	Or(conds ...gen.Condition) INovelDo
	Select(conds ...field.Expr) INovelDo
	Where(conds ...gen.Condition) INovelDo
	Order(conds ...field.Expr) INovelDo
	Distinct(cols ...field.Expr) INovelDo
	Omit(cols ...field.Expr) INovelDo
	Join(table schema.Tabler, on ...field.Expr) INovelDo
	LeftJoin(table schema.Tabler, on ...field.Expr) INovelDo
	RightJoin(table schema.Tabler, on ...field.Expr) INovelDo
	Group(cols ...field.Expr) INovelDo
	Having(conds ...gen.Condition) INovelDo
	Limit(limit int) INovelDo
	Offset(offset int) INovelDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) INovelDo
	Unscoped() INovelDo
	Create(values ...*db_model.Novel) error
	CreateInBatches(values []*db_model.Novel, batchSize int) error
	Save(values ...*db_model.Novel) error
	First() (*db_model.Novel, error)
	Take() (*db_model.Novel, error)
	Last() (*db_model.Novel, error)
	Find() ([]*db_model.Novel, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*db_model.Novel, err error)
	FindInBatches(result *[]*db_model.Novel, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*db_model.Novel) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) INovelDo
	Assign(attrs ...field.AssignExpr) INovelDo
	Joins(fields ...field.RelationField) INovelDo
	Preload(fields ...field.RelationField) INovelDo
	FirstOrInit() (*db_model.Novel, error)
	FirstOrCreate() (*db_model.Novel, error)
	FindByPage(offset int, limit int) (result []*db_model.Novel, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Rows() (*sql.Rows, error)
	Row() *sql.Row
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) INovelDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (n novelDo) Debug() INovelDo {
	return n.withDO(n.DO.Debug())
}

func (n novelDo) WithContext(ctx context.Context) INovelDo {
	return n.withDO(n.DO.WithContext(ctx))
}

func (n novelDo) ReadDB() INovelDo {
	return n.Clauses(dbresolver.Read)
}

func (n novelDo) WriteDB() INovelDo {
	return n.Clauses(dbresolver.Write)
}

func (n novelDo) Session(config *gorm.Session) INovelDo {
	return n.withDO(n.DO.Session(config))
}

func (n novelDo) Clauses(conds ...clause.Expression) INovelDo {
	return n.withDO(n.DO.Clauses(conds...))
}

func (n novelDo) Returning(value interface{}, columns ...string) INovelDo {
	return n.withDO(n.DO.Returning(value, columns...))
}

func (n novelDo) Not(conds ...gen.Condition) INovelDo {
	return n.withDO(n.DO.Not(conds...))
}

func (n novelDo) Or(conds ...gen.Condition) INovelDo {
	return n.withDO(n.DO.Or(conds...))
}

func (n novelDo) Select(conds ...field.Expr) INovelDo {
	return n.withDO(n.DO.Select(conds...))
}

func (n novelDo) Where(conds ...gen.Condition) INovelDo {
	return n.withDO(n.DO.Where(conds...))
}

func (n novelDo) Order(conds ...field.Expr) INovelDo {
	return n.withDO(n.DO.Order(conds...))
}

func (n novelDo) Distinct(cols ...field.Expr) INovelDo {
	return n.withDO(n.DO.Distinct(cols...))
}

func (n novelDo) Omit(cols ...field.Expr) INovelDo {
	return n.withDO(n.DO.Omit(cols...))
}

func (n novelDo) Join(table schema.Tabler, on ...field.Expr) INovelDo {
	return n.withDO(n.DO.Join(table, on...))
}

func (n novelDo) LeftJoin(table schema.Tabler, on ...field.Expr) INovelDo {
	return n.withDO(n.DO.LeftJoin(table, on...))
}

func (n novelDo) RightJoin(table schema.Tabler, on ...field.Expr) INovelDo {
	return n.withDO(n.DO.RightJoin(table, on...))
}

func (n novelDo) Group(cols ...field.Expr) INovelDo {
	return n.withDO(n.DO.Group(cols...))
}

func (n novelDo) Having(conds ...gen.Condition) INovelDo {
	return n.withDO(n.DO.Having(conds...))
}

func (n novelDo) Limit(limit int) INovelDo {
	return n.withDO(n.DO.Limit(limit))
}

func (n novelDo) Offset(offset int) INovelDo {
	return n.withDO(n.DO.Offset(offset))
}

func (n novelDo) Scopes(funcs ...func(gen.Dao) gen.Dao) INovelDo {
	return n.withDO(n.DO.Scopes(funcs...))
}

func (n novelDo) Unscoped() INovelDo {
	return n.withDO(n.DO.Unscoped())
}

func (n novelDo) Create(values ...*db_model.Novel) error {
	if len(values) == 0 {
		return nil
	}
	return n.DO.Create(values)
}

func (n novelDo) CreateInBatches(values []*db_model.Novel, batchSize int) error {
	return n.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (n novelDo) Save(values ...*db_model.Novel) error {
	if len(values) == 0 {
		return nil
	}
	return n.DO.Save(values)
}

func (n novelDo) First() (*db_model.Novel, error) {
	if result, err := n.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*db_model.Novel), nil
	}
}

func (n novelDo) Take() (*db_model.Novel, error) {
	if result, err := n.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*db_model.Novel), nil
	}
}

func (n novelDo) Last() (*db_model.Novel, error) {
	if result, err := n.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*db_model.Novel), nil
	}
}

func (n novelDo) Find() ([]*db_model.Novel, error) {
	result, err := n.DO.Find()
	return result.([]*db_model.Novel), err
}

func (n novelDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*db_model.Novel, err error) {
	buf := make([]*db_model.Novel, 0, batchSize)
	err = n.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (n novelDo) FindInBatches(result *[]*db_model.Novel, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return n.DO.FindInBatches(result, batchSize, fc)
}

func (n novelDo) Attrs(attrs ...field.AssignExpr) INovelDo {
	return n.withDO(n.DO.Attrs(attrs...))
}

func (n novelDo) Assign(attrs ...field.AssignExpr) INovelDo {
	return n.withDO(n.DO.Assign(attrs...))
}

func (n novelDo) Joins(fields ...field.RelationField) INovelDo {
	for _, _f := range fields {
		n = *n.withDO(n.DO.Joins(_f))
	}
	return &n
}

func (n novelDo) Preload(fields ...field.RelationField) INovelDo {
	for _, _f := range fields {
		n = *n.withDO(n.DO.Preload(_f))
	}
	return &n
}

func (n novelDo) FirstOrInit() (*db_model.Novel, error) {
	if result, err := n.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*db_model.Novel), nil
	}
}

func (n novelDo) FirstOrCreate() (*db_model.Novel, error) {
	if result, err := n.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*db_model.Novel), nil
	}
}

func (n novelDo) FindByPage(offset int, limit int) (result []*db_model.Novel, count int64, err error) {
	result, err = n.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = n.Offset(-1).Limit(-1).Count()
	return
}

func (n novelDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = n.Count()
	if err != nil {
		return
	}

	err = n.Offset(offset).Limit(limit).Scan(result)
	return
}

func (n novelDo) Scan(result interface{}) (err error) {
	return n.DO.Scan(result)
}

func (n novelDo) Delete(models ...*db_model.Novel) (result gen.ResultInfo, err error) {
	return n.DO.Delete(models)
}

func (n *novelDo) withDO(do gen.Dao) *novelDo {
	n.DO = *do.(*gen.DO)
	return n
}
