// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"
	"database/sql"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"main/db/db_model"
)

func newNovelContent(db *gorm.DB, opts ...gen.DOOption) novelContent {
	_novelContent := novelContent{}

	_novelContent.novelContentDo.UseDB(db, opts...)
	_novelContent.novelContentDo.UseModel(&db_model.NovelContent{})

	tableName := _novelContent.novelContentDo.TableName()
	_novelContent.ALL = field.NewAsterisk(tableName)
	_novelContent.ID = field.NewString(tableName, "id")
	_novelContent.ChapterName = field.NewString(tableName, "chapter_name")
	_novelContent.NovelID = field.NewString(tableName, "novel_id")
	_novelContent.OwnerUserAccountID = field.NewString(tableName, "owner_user_account_id")
	_novelContent.ParentContentsID = field.NewString(tableName, "parent_contents_id")
	_novelContent.DisplayOrder = field.NewInt32(tableName, "display_order")
	_novelContent.Contents = field.NewString(tableName, "contents")
	_novelContent.Description = field.NewString(tableName, "description")

	_novelContent.fillFieldMap()

	return _novelContent
}

type novelContent struct {
	novelContentDo novelContentDo

	ALL                field.Asterisk
	ID                 field.String
	ChapterName        field.String
	NovelID            field.String
	OwnerUserAccountID field.String
	ParentContentsID   field.String
	DisplayOrder       field.Int32
	Contents           field.String
	Description        field.String

	fieldMap map[string]field.Expr
}

func (n novelContent) Table(newTableName string) *novelContent {
	n.novelContentDo.UseTable(newTableName)
	return n.updateTableName(newTableName)
}

func (n novelContent) As(alias string) *novelContent {
	n.novelContentDo.DO = *(n.novelContentDo.As(alias).(*gen.DO))
	return n.updateTableName(alias)
}

func (n *novelContent) updateTableName(table string) *novelContent {
	n.ALL = field.NewAsterisk(table)
	n.ID = field.NewString(table, "id")
	n.ChapterName = field.NewString(table, "chapter_name")
	n.NovelID = field.NewString(table, "novel_id")
	n.OwnerUserAccountID = field.NewString(table, "owner_user_account_id")
	n.ParentContentsID = field.NewString(table, "parent_contents_id")
	n.DisplayOrder = field.NewInt32(table, "display_order")
	n.Contents = field.NewString(table, "contents")
	n.Description = field.NewString(table, "description")

	n.fillFieldMap()

	return n
}

func (n *novelContent) WithContext(ctx context.Context) INovelContentDo {
	return n.novelContentDo.WithContext(ctx)
}

func (n novelContent) TableName() string { return n.novelContentDo.TableName() }

func (n novelContent) Alias() string { return n.novelContentDo.Alias() }

func (n novelContent) Columns(cols ...field.Expr) gen.Columns {
	return n.novelContentDo.Columns(cols...)
}

func (n *novelContent) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := n.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (n *novelContent) fillFieldMap() {
	n.fieldMap = make(map[string]field.Expr, 8)
	n.fieldMap["id"] = n.ID
	n.fieldMap["chapter_name"] = n.ChapterName
	n.fieldMap["novel_id"] = n.NovelID
	n.fieldMap["owner_user_account_id"] = n.OwnerUserAccountID
	n.fieldMap["parent_contents_id"] = n.ParentContentsID
	n.fieldMap["display_order"] = n.DisplayOrder
	n.fieldMap["contents"] = n.Contents
	n.fieldMap["description"] = n.Description
}

func (n novelContent) clone(db *gorm.DB) novelContent {
	n.novelContentDo.ReplaceConnPool(db.Statement.ConnPool)
	return n
}

func (n novelContent) replaceDB(db *gorm.DB) novelContent {
	n.novelContentDo.ReplaceDB(db)
	return n
}

type novelContentDo struct{ gen.DO }

type INovelContentDo interface {
	gen.SubQuery
	Debug() INovelContentDo
	WithContext(ctx context.Context) INovelContentDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() INovelContentDo
	WriteDB() INovelContentDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) INovelContentDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) INovelContentDo
	Not(conds ...gen.Condition) INovelContentDo
	Or(conds ...gen.Condition) INovelContentDo
	Select(conds ...field.Expr) INovelContentDo
	Where(conds ...gen.Condition) INovelContentDo
	Order(conds ...field.Expr) INovelContentDo
	Distinct(cols ...field.Expr) INovelContentDo
	Omit(cols ...field.Expr) INovelContentDo
	Join(table schema.Tabler, on ...field.Expr) INovelContentDo
	LeftJoin(table schema.Tabler, on ...field.Expr) INovelContentDo
	RightJoin(table schema.Tabler, on ...field.Expr) INovelContentDo
	Group(cols ...field.Expr) INovelContentDo
	Having(conds ...gen.Condition) INovelContentDo
	Limit(limit int) INovelContentDo
	Offset(offset int) INovelContentDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) INovelContentDo
	Unscoped() INovelContentDo
	Create(values ...*db_model.NovelContent) error
	CreateInBatches(values []*db_model.NovelContent, batchSize int) error
	Save(values ...*db_model.NovelContent) error
	First() (*db_model.NovelContent, error)
	Take() (*db_model.NovelContent, error)
	Last() (*db_model.NovelContent, error)
	Find() ([]*db_model.NovelContent, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*db_model.NovelContent, err error)
	FindInBatches(result *[]*db_model.NovelContent, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*db_model.NovelContent) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) INovelContentDo
	Assign(attrs ...field.AssignExpr) INovelContentDo
	Joins(fields ...field.RelationField) INovelContentDo
	Preload(fields ...field.RelationField) INovelContentDo
	FirstOrInit() (*db_model.NovelContent, error)
	FirstOrCreate() (*db_model.NovelContent, error)
	FindByPage(offset int, limit int) (result []*db_model.NovelContent, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Rows() (*sql.Rows, error)
	Row() *sql.Row
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) INovelContentDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (n novelContentDo) Debug() INovelContentDo {
	return n.withDO(n.DO.Debug())
}

func (n novelContentDo) WithContext(ctx context.Context) INovelContentDo {
	return n.withDO(n.DO.WithContext(ctx))
}

func (n novelContentDo) ReadDB() INovelContentDo {
	return n.Clauses(dbresolver.Read)
}

func (n novelContentDo) WriteDB() INovelContentDo {
	return n.Clauses(dbresolver.Write)
}

func (n novelContentDo) Session(config *gorm.Session) INovelContentDo {
	return n.withDO(n.DO.Session(config))
}

func (n novelContentDo) Clauses(conds ...clause.Expression) INovelContentDo {
	return n.withDO(n.DO.Clauses(conds...))
}

func (n novelContentDo) Returning(value interface{}, columns ...string) INovelContentDo {
	return n.withDO(n.DO.Returning(value, columns...))
}

func (n novelContentDo) Not(conds ...gen.Condition) INovelContentDo {
	return n.withDO(n.DO.Not(conds...))
}

func (n novelContentDo) Or(conds ...gen.Condition) INovelContentDo {
	return n.withDO(n.DO.Or(conds...))
}

func (n novelContentDo) Select(conds ...field.Expr) INovelContentDo {
	return n.withDO(n.DO.Select(conds...))
}

func (n novelContentDo) Where(conds ...gen.Condition) INovelContentDo {
	return n.withDO(n.DO.Where(conds...))
}

func (n novelContentDo) Order(conds ...field.Expr) INovelContentDo {
	return n.withDO(n.DO.Order(conds...))
}

func (n novelContentDo) Distinct(cols ...field.Expr) INovelContentDo {
	return n.withDO(n.DO.Distinct(cols...))
}

func (n novelContentDo) Omit(cols ...field.Expr) INovelContentDo {
	return n.withDO(n.DO.Omit(cols...))
}

func (n novelContentDo) Join(table schema.Tabler, on ...field.Expr) INovelContentDo {
	return n.withDO(n.DO.Join(table, on...))
}

func (n novelContentDo) LeftJoin(table schema.Tabler, on ...field.Expr) INovelContentDo {
	return n.withDO(n.DO.LeftJoin(table, on...))
}

func (n novelContentDo) RightJoin(table schema.Tabler, on ...field.Expr) INovelContentDo {
	return n.withDO(n.DO.RightJoin(table, on...))
}

func (n novelContentDo) Group(cols ...field.Expr) INovelContentDo {
	return n.withDO(n.DO.Group(cols...))
}

func (n novelContentDo) Having(conds ...gen.Condition) INovelContentDo {
	return n.withDO(n.DO.Having(conds...))
}

func (n novelContentDo) Limit(limit int) INovelContentDo {
	return n.withDO(n.DO.Limit(limit))
}

func (n novelContentDo) Offset(offset int) INovelContentDo {
	return n.withDO(n.DO.Offset(offset))
}

func (n novelContentDo) Scopes(funcs ...func(gen.Dao) gen.Dao) INovelContentDo {
	return n.withDO(n.DO.Scopes(funcs...))
}

func (n novelContentDo) Unscoped() INovelContentDo {
	return n.withDO(n.DO.Unscoped())
}

func (n novelContentDo) Create(values ...*db_model.NovelContent) error {
	if len(values) == 0 {
		return nil
	}
	return n.DO.Create(values)
}

func (n novelContentDo) CreateInBatches(values []*db_model.NovelContent, batchSize int) error {
	return n.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (n novelContentDo) Save(values ...*db_model.NovelContent) error {
	if len(values) == 0 {
		return nil
	}
	return n.DO.Save(values)
}

func (n novelContentDo) First() (*db_model.NovelContent, error) {
	if result, err := n.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*db_model.NovelContent), nil
	}
}

func (n novelContentDo) Take() (*db_model.NovelContent, error) {
	if result, err := n.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*db_model.NovelContent), nil
	}
}

func (n novelContentDo) Last() (*db_model.NovelContent, error) {
	if result, err := n.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*db_model.NovelContent), nil
	}
}

func (n novelContentDo) Find() ([]*db_model.NovelContent, error) {
	result, err := n.DO.Find()
	return result.([]*db_model.NovelContent), err
}

func (n novelContentDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*db_model.NovelContent, err error) {
	buf := make([]*db_model.NovelContent, 0, batchSize)
	err = n.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (n novelContentDo) FindInBatches(result *[]*db_model.NovelContent, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return n.DO.FindInBatches(result, batchSize, fc)
}

func (n novelContentDo) Attrs(attrs ...field.AssignExpr) INovelContentDo {
	return n.withDO(n.DO.Attrs(attrs...))
}

func (n novelContentDo) Assign(attrs ...field.AssignExpr) INovelContentDo {
	return n.withDO(n.DO.Assign(attrs...))
}

func (n novelContentDo) Joins(fields ...field.RelationField) INovelContentDo {
	for _, _f := range fields {
		n = *n.withDO(n.DO.Joins(_f))
	}
	return &n
}

func (n novelContentDo) Preload(fields ...field.RelationField) INovelContentDo {
	for _, _f := range fields {
		n = *n.withDO(n.DO.Preload(_f))
	}
	return &n
}

func (n novelContentDo) FirstOrInit() (*db_model.NovelContent, error) {
	if result, err := n.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*db_model.NovelContent), nil
	}
}

func (n novelContentDo) FirstOrCreate() (*db_model.NovelContent, error) {
	if result, err := n.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*db_model.NovelContent), nil
	}
}

func (n novelContentDo) FindByPage(offset int, limit int) (result []*db_model.NovelContent, count int64, err error) {
	result, err = n.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = n.Offset(-1).Limit(-1).Count()
	return
}

func (n novelContentDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = n.Count()
	if err != nil {
		return
	}

	err = n.Offset(offset).Limit(limit).Scan(result)
	return
}

func (n novelContentDo) Scan(result interface{}) (err error) {
	return n.DO.Scan(result)
}

func (n novelContentDo) Delete(models ...*db_model.NovelContent) (result gen.ResultInfo, err error) {
	return n.DO.Delete(models)
}

func (n *novelContentDo) withDO(do gen.Dao) *novelContentDo {
	n.DO = *do.(*gen.DO)
	return n
}
