// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"
	"database/sql"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"main/db/db_model"
)

func newNovelSetting(db *gorm.DB, opts ...gen.DOOption) novelSetting {
	_novelSetting := novelSetting{}

	_novelSetting.novelSettingDo.UseDB(db, opts...)
	_novelSetting.novelSettingDo.UseModel(&db_model.NovelSetting{})

	tableName := _novelSetting.novelSettingDo.TableName()
	_novelSetting.ALL = field.NewAsterisk(tableName)
	_novelSetting.ID = field.NewString(tableName, "id")
	_novelSetting.Name = field.NewString(tableName, "name")
	_novelSetting.NovelID = field.NewString(tableName, "novel_id")
	_novelSetting.OwnerUserAccountID = field.NewString(tableName, "owner_user_account_id")
	_novelSetting.ParentSettingID = field.NewString(tableName, "parent_setting_id")
	_novelSetting.DisplayOrder = field.NewInt32(tableName, "display_order")
	_novelSetting.Attributes = field.NewField(tableName, "attributes")
	_novelSetting.Description = field.NewString(tableName, "description")

	_novelSetting.fillFieldMap()

	return _novelSetting
}

type novelSetting struct {
	novelSettingDo novelSettingDo

	ALL                field.Asterisk
	ID                 field.String
	Name               field.String
	NovelID            field.String
	OwnerUserAccountID field.String
	ParentSettingID    field.String
	DisplayOrder       field.Int32
	Attributes         field.Field
	Description        field.String

	fieldMap map[string]field.Expr
}

func (n novelSetting) Table(newTableName string) *novelSetting {
	n.novelSettingDo.UseTable(newTableName)
	return n.updateTableName(newTableName)
}

func (n novelSetting) As(alias string) *novelSetting {
	n.novelSettingDo.DO = *(n.novelSettingDo.As(alias).(*gen.DO))
	return n.updateTableName(alias)
}

func (n *novelSetting) updateTableName(table string) *novelSetting {
	n.ALL = field.NewAsterisk(table)
	n.ID = field.NewString(table, "id")
	n.Name = field.NewString(table, "name")
	n.NovelID = field.NewString(table, "novel_id")
	n.OwnerUserAccountID = field.NewString(table, "owner_user_account_id")
	n.ParentSettingID = field.NewString(table, "parent_setting_id")
	n.DisplayOrder = field.NewInt32(table, "display_order")
	n.Attributes = field.NewField(table, "attributes")
	n.Description = field.NewString(table, "description")

	n.fillFieldMap()

	return n
}

func (n *novelSetting) WithContext(ctx context.Context) INovelSettingDo {
	return n.novelSettingDo.WithContext(ctx)
}

func (n novelSetting) TableName() string { return n.novelSettingDo.TableName() }

func (n novelSetting) Alias() string { return n.novelSettingDo.Alias() }

func (n novelSetting) Columns(cols ...field.Expr) gen.Columns {
	return n.novelSettingDo.Columns(cols...)
}

func (n *novelSetting) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := n.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (n *novelSetting) fillFieldMap() {
	n.fieldMap = make(map[string]field.Expr, 8)
	n.fieldMap["id"] = n.ID
	n.fieldMap["name"] = n.Name
	n.fieldMap["novel_id"] = n.NovelID
	n.fieldMap["owner_user_account_id"] = n.OwnerUserAccountID
	n.fieldMap["parent_setting_id"] = n.ParentSettingID
	n.fieldMap["display_order"] = n.DisplayOrder
	n.fieldMap["attributes"] = n.Attributes
	n.fieldMap["description"] = n.Description
}

func (n novelSetting) clone(db *gorm.DB) novelSetting {
	n.novelSettingDo.ReplaceConnPool(db.Statement.ConnPool)
	return n
}

func (n novelSetting) replaceDB(db *gorm.DB) novelSetting {
	n.novelSettingDo.ReplaceDB(db)
	return n
}

type novelSettingDo struct{ gen.DO }

type INovelSettingDo interface {
	gen.SubQuery
	Debug() INovelSettingDo
	WithContext(ctx context.Context) INovelSettingDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() INovelSettingDo
	WriteDB() INovelSettingDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) INovelSettingDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) INovelSettingDo
	Not(conds ...gen.Condition) INovelSettingDo
	Or(conds ...gen.Condition) INovelSettingDo
	Select(conds ...field.Expr) INovelSettingDo
	Where(conds ...gen.Condition) INovelSettingDo
	Order(conds ...field.Expr) INovelSettingDo
	Distinct(cols ...field.Expr) INovelSettingDo
	Omit(cols ...field.Expr) INovelSettingDo
	Join(table schema.Tabler, on ...field.Expr) INovelSettingDo
	LeftJoin(table schema.Tabler, on ...field.Expr) INovelSettingDo
	RightJoin(table schema.Tabler, on ...field.Expr) INovelSettingDo
	Group(cols ...field.Expr) INovelSettingDo
	Having(conds ...gen.Condition) INovelSettingDo
	Limit(limit int) INovelSettingDo
	Offset(offset int) INovelSettingDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) INovelSettingDo
	Unscoped() INovelSettingDo
	Create(values ...*db_model.NovelSetting) error
	CreateInBatches(values []*db_model.NovelSetting, batchSize int) error
	Save(values ...*db_model.NovelSetting) error
	First() (*db_model.NovelSetting, error)
	Take() (*db_model.NovelSetting, error)
	Last() (*db_model.NovelSetting, error)
	Find() ([]*db_model.NovelSetting, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*db_model.NovelSetting, err error)
	FindInBatches(result *[]*db_model.NovelSetting, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*db_model.NovelSetting) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) INovelSettingDo
	Assign(attrs ...field.AssignExpr) INovelSettingDo
	Joins(fields ...field.RelationField) INovelSettingDo
	Preload(fields ...field.RelationField) INovelSettingDo
	FirstOrInit() (*db_model.NovelSetting, error)
	FirstOrCreate() (*db_model.NovelSetting, error)
	FindByPage(offset int, limit int) (result []*db_model.NovelSetting, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Rows() (*sql.Rows, error)
	Row() *sql.Row
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) INovelSettingDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (n novelSettingDo) Debug() INovelSettingDo {
	return n.withDO(n.DO.Debug())
}

func (n novelSettingDo) WithContext(ctx context.Context) INovelSettingDo {
	return n.withDO(n.DO.WithContext(ctx))
}

func (n novelSettingDo) ReadDB() INovelSettingDo {
	return n.Clauses(dbresolver.Read)
}

func (n novelSettingDo) WriteDB() INovelSettingDo {
	return n.Clauses(dbresolver.Write)
}

func (n novelSettingDo) Session(config *gorm.Session) INovelSettingDo {
	return n.withDO(n.DO.Session(config))
}

func (n novelSettingDo) Clauses(conds ...clause.Expression) INovelSettingDo {
	return n.withDO(n.DO.Clauses(conds...))
}

func (n novelSettingDo) Returning(value interface{}, columns ...string) INovelSettingDo {
	return n.withDO(n.DO.Returning(value, columns...))
}

func (n novelSettingDo) Not(conds ...gen.Condition) INovelSettingDo {
	return n.withDO(n.DO.Not(conds...))
}

func (n novelSettingDo) Or(conds ...gen.Condition) INovelSettingDo {
	return n.withDO(n.DO.Or(conds...))
}

func (n novelSettingDo) Select(conds ...field.Expr) INovelSettingDo {
	return n.withDO(n.DO.Select(conds...))
}

func (n novelSettingDo) Where(conds ...gen.Condition) INovelSettingDo {
	return n.withDO(n.DO.Where(conds...))
}

func (n novelSettingDo) Order(conds ...field.Expr) INovelSettingDo {
	return n.withDO(n.DO.Order(conds...))
}

func (n novelSettingDo) Distinct(cols ...field.Expr) INovelSettingDo {
	return n.withDO(n.DO.Distinct(cols...))
}

func (n novelSettingDo) Omit(cols ...field.Expr) INovelSettingDo {
	return n.withDO(n.DO.Omit(cols...))
}

func (n novelSettingDo) Join(table schema.Tabler, on ...field.Expr) INovelSettingDo {
	return n.withDO(n.DO.Join(table, on...))
}

func (n novelSettingDo) LeftJoin(table schema.Tabler, on ...field.Expr) INovelSettingDo {
	return n.withDO(n.DO.LeftJoin(table, on...))
}

func (n novelSettingDo) RightJoin(table schema.Tabler, on ...field.Expr) INovelSettingDo {
	return n.withDO(n.DO.RightJoin(table, on...))
}

func (n novelSettingDo) Group(cols ...field.Expr) INovelSettingDo {
	return n.withDO(n.DO.Group(cols...))
}

func (n novelSettingDo) Having(conds ...gen.Condition) INovelSettingDo {
	return n.withDO(n.DO.Having(conds...))
}

func (n novelSettingDo) Limit(limit int) INovelSettingDo {
	return n.withDO(n.DO.Limit(limit))
}

func (n novelSettingDo) Offset(offset int) INovelSettingDo {
	return n.withDO(n.DO.Offset(offset))
}

func (n novelSettingDo) Scopes(funcs ...func(gen.Dao) gen.Dao) INovelSettingDo {
	return n.withDO(n.DO.Scopes(funcs...))
}

func (n novelSettingDo) Unscoped() INovelSettingDo {
	return n.withDO(n.DO.Unscoped())
}

func (n novelSettingDo) Create(values ...*db_model.NovelSetting) error {
	if len(values) == 0 {
		return nil
	}
	return n.DO.Create(values)
}

func (n novelSettingDo) CreateInBatches(values []*db_model.NovelSetting, batchSize int) error {
	return n.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (n novelSettingDo) Save(values ...*db_model.NovelSetting) error {
	if len(values) == 0 {
		return nil
	}
	return n.DO.Save(values)
}

func (n novelSettingDo) First() (*db_model.NovelSetting, error) {
	if result, err := n.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*db_model.NovelSetting), nil
	}
}

func (n novelSettingDo) Take() (*db_model.NovelSetting, error) {
	if result, err := n.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*db_model.NovelSetting), nil
	}
}

func (n novelSettingDo) Last() (*db_model.NovelSetting, error) {
	if result, err := n.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*db_model.NovelSetting), nil
	}
}

func (n novelSettingDo) Find() ([]*db_model.NovelSetting, error) {
	result, err := n.DO.Find()
	return result.([]*db_model.NovelSetting), err
}

func (n novelSettingDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*db_model.NovelSetting, err error) {
	buf := make([]*db_model.NovelSetting, 0, batchSize)
	err = n.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (n novelSettingDo) FindInBatches(result *[]*db_model.NovelSetting, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return n.DO.FindInBatches(result, batchSize, fc)
}

func (n novelSettingDo) Attrs(attrs ...field.AssignExpr) INovelSettingDo {
	return n.withDO(n.DO.Attrs(attrs...))
}

func (n novelSettingDo) Assign(attrs ...field.AssignExpr) INovelSettingDo {
	return n.withDO(n.DO.Assign(attrs...))
}

func (n novelSettingDo) Joins(fields ...field.RelationField) INovelSettingDo {
	for _, _f := range fields {
		n = *n.withDO(n.DO.Joins(_f))
	}
	return &n
}

func (n novelSettingDo) Preload(fields ...field.RelationField) INovelSettingDo {
	for _, _f := range fields {
		n = *n.withDO(n.DO.Preload(_f))
	}
	return &n
}

func (n novelSettingDo) FirstOrInit() (*db_model.NovelSetting, error) {
	if result, err := n.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*db_model.NovelSetting), nil
	}
}

func (n novelSettingDo) FirstOrCreate() (*db_model.NovelSetting, error) {
	if result, err := n.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*db_model.NovelSetting), nil
	}
}

func (n novelSettingDo) FindByPage(offset int, limit int) (result []*db_model.NovelSetting, count int64, err error) {
	result, err = n.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = n.Offset(-1).Limit(-1).Count()
	return
}

func (n novelSettingDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = n.Count()
	if err != nil {
		return
	}

	err = n.Offset(offset).Limit(limit).Scan(result)
	return
}

func (n novelSettingDo) Scan(result interface{}) (err error) {
	return n.DO.Scan(result)
}

func (n novelSettingDo) Delete(models ...*db_model.NovelSetting) (result gen.ResultInfo, err error) {
	return n.DO.Delete(models)
}

func (n *novelSettingDo) withDO(do gen.Dao) *novelSettingDo {
	n.DO = *do.(*gen.DO)
	return n
}
